### ISSUE TITLE
Wrong type called in example.ipynb

### ISSUE THREAD

**Issue by gnunziante4** [Alexander-Barth/DataAssim.jl#17]
Hi,

I found in this line of example.ipynb

`xai, = fourDVar(xi, Pi, ℳ, yo, R, H, nmax, no);
`

this error

```
ERROR: LoadError: MethodError: no method matching fourDVar(::Vector{Int64}, ::Matrix{Bool}, ::ModelMatrix{Matrix{Float64}}, ::Matrix{Float64}, ::Matrix{Float64}, ::Matrix{Int64}, ::Int64, ::StepRange{Int64, Int64})

You might have used a 2d row vector where a 1d column vector was required.
Note the difference between 1d column vector [1,2,3] and 2d row vector [1 2 3].
You can convert to a column vector with the vec() function.

Closest candidates are:
  fourDVar(::AbstractVector, ::Any, ::Any, **::AbstractVector**, **::AbstractVector**, ::Any, ::Any, ::Any; innerloops, outerloops, tol)
```
in particular yo and R are defined as AbstractVector in fourDVar function defined in fourDVar.jl
while in example.ipynb they are defined as Matrix{Float64}

```
m=1;

R = 0.1 * Matrix(I, m, m)

no = 10:5:nmax
yo = randn(m, length(no))
```

Thank you in advance for your support!

**Comment by Alexander-Barth** [comment]
Thank you for letting me know! I just update the example.ipynb. Does it also work for you now?

**Comment by gnunziante4** [comment]
> Thank you for letting me know! I just update the example.ipynb. Does it also work for you now?

It perfectly works! Thank you

**Comment by Alexander-Barth** [comment]
Thanks for checking and your time to provide the feed-back!
