### ISSUE TITLE
Plans for DataAssim?

### ISSUE THREAD

**Issue by Balinus** [Alexander-Barth/DataAssim.jl#6]
Hello!

I'm doing some prospective work on data assimilation. I'm gathering which packages or solutions is available (in any languages actually).

I was wondering two things with respect to DataAssim:

1. Is there a notebook or examples somewhere that demonstrate how to use the package? Perhaps I'm dense but I don't fully grasp the details.
2. Is there a plan to also introduce other types of assimilation such as particle filter? Or a simple Kalman filter (seems the method are only of the ensemble type).

Thanks for your time and any info!

**Comment by Alexander-Barth** [comment]
I just added a notebook on how to use a simple Kalman Filter and 4D-Var scheme with a toy-model. I hope this helps. I do not have plans (at least in the near-term to include) a particle filter.

https://nbviewer.jupyter.org/github/Alexander-Barth/DataAssim.jl/blob/master/examples/example.ipynb

**Comment by Balinus** [comment]
Awesome! Thanks! :)
